services:
  postgres:
    image: postgres
    container_name: postgres_db
    networks:
      my_custom_network:
        ipv4_address: 172.19.0.4
    environment:
      POSTGRES_USER: bojjoo
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: Educonnect
    ports:
      - "9999:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata/data:/var/lib/postgresql/data  # Volume để lưu trữ database PostgreSQL

  fastapi:
    build: .
    container_name: fastapi_app
    networks:
      my_custom_network:
        ipv4_address: 172.19.0.5
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    depends_on:
      - postgres


  nginx:
    image: nginx:latest
    container_name: demo_nginx_gpt
    networks:
      my_custom_network:
        ipv4_address: 172.19.0.2
    ports:
      - "90:90"
    depends_on:
      - fastapi
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
